/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessToken: () => import('#controllers/access_token_controller'),
  Bet: () => import('#controllers/bet_controller'),
  GoogleAuth: () => import('#controllers/google_auth_controller'),
  League: () => import('#controllers/league_controller'),
  LeagueMember: () => import('#controllers/league_member_controller'),
  LeagueRace: () => import('#controllers/league_race_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  PasswordReset: () => import('#controllers/password_reset_controller'),
  Profile: () => import('#controllers/profile_controller'),
  PushSubscription: () => import('#controllers/push_subscription_controller'),
  Race: () => import('#controllers/race_controller'),
  RaceSync: () => import('#controllers/race_sync_controller'),
  Standings: () => import('#controllers/standings_controller'),
  Stats: () => import('#controllers/stats_controller'),
  Feed: () => import('#controllers/feed_controller'),
  MemberProfile: () => import('#controllers/member_profile_controller'),
}
