/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class BetsClassicSchema extends BaseModel {
  static $columns = ['bonusRiderId', 'createdAt', 'favoriteRiderId', 'id', 'placedAt', 'raceId', 'status', 'updatedAt', 'userId'] as const
  $columns = BetsClassicSchema.$columns
  @column()
  declare bonusRiderId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare favoriteRiderId: string
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime()
  declare placedAt: DateTime
  @column()
  declare raceId: string
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: string
}

export class BetsGrandTourSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'placedAt', 'raceId', 'status', 'updatedAt', 'userId'] as const
  $columns = BetsGrandTourSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime()
  declare placedAt: DateTime
  @column()
  declare raceId: string
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: string
}

export class BetsGrandTourRiderSchema extends BaseModel {
  static $columns = ['betId', 'id', 'riderId'] as const
  $columns = BetsGrandTourRiderSchema.$columns
  @column()
  declare betId: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare riderId: string
}

export class LeagueMemberSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'isAdmin', 'joinedAt', 'leagueId', 'updatedAt', 'userId'] as const
  $columns = LeagueMemberSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isAdmin: boolean
  @column.dateTime()
  declare joinedAt: DateTime
  @column()
  declare leagueId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: string
}

export class LeagueRaceSchema extends BaseModel {
  static $columns = ['addedAt', 'id', 'leagueId', 'raceId'] as const
  $columns = LeagueRaceSchema.$columns
  @column.dateTime()
  declare addedAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare leagueId: string
  @column()
  declare raceId: string
}

export class LeagueSchema extends BaseModel {
  static $columns = ['code', 'createdAt', 'createdBy', 'id', 'name', 'season', 'updatedAt'] as const
  $columns = LeagueSchema.$columns
  @column()
  declare code: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdBy: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare season: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class PasswordResetTokenSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'expiresAt', 'id', 'token'] as const
  $columns = PasswordResetTokenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare token: string
}

export class PushSubscriptionSchema extends BaseModel {
  static $columns = ['auth', 'createdAt', 'endpoint', 'id', 'p256Dh', 'updatedAt', 'userId'] as const
  $columns = PushSubscriptionSchema.$columns
  @column()
  declare auth: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare endpoint: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare p256Dh: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: string
}

export class RaceRiderCostSchema extends BaseModel {
  static $columns = ['cost', 'id', 'pcsRank', 'raceId', 'riderId', 'snapshottedAt'] as const
  $columns = RaceRiderCostSchema.$columns
  @column()
  declare cost: number
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare pcsRank: number | null
  @column()
  declare raceId: string
  @column()
  declare riderId: string
  @column.dateTime()
  declare snapshottedAt: DateTime
}

export class RaceSchema extends BaseModel {
  static $columns = ['createdAt', 'endAt', 'id', 'isGrandTour', 'lastSyncedAt', 'multiplierType', 'name', 'raceType', 'reminder1HSentAt', 'reminder24HSentAt', 'reminder5HSentAt', 'resultsFinal', 'seasonYear', 'slug', 'stageCount', 'startAt', 'status', 'updatedAt'] as const
  $columns = RaceSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare endAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isGrandTour: boolean
  @column.dateTime()
  declare lastSyncedAt: DateTime | null
  @column()
  declare multiplierType: string
  @column()
  declare name: string
  @column()
  declare raceType: string
  @column.dateTime()
  declare reminder1HSentAt: DateTime | null
  @column.dateTime()
  declare reminder24HSentAt: DateTime | null
  @column.dateTime()
  declare reminder5HSentAt: DateTime | null
  @column()
  declare resultsFinal: boolean
  @column()
  declare seasonYear: number
  @column()
  declare slug: string
  @column()
  declare stageCount: number | null
  @column.dateTime()
  declare startAt: DateTime | null
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class RiderSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'nationality', 'pcsUrl', 'updatedAt'] as const
  $columns = RiderSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare nationality: string | null
  @column()
  declare pcsUrl: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ScoreSchema extends BaseModel {
  static $columns = ['id', 'leagueId', 'maxPossible', 'points', 'raceId', 'updatedAt', 'userId'] as const
  $columns = ScoreSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare leagueId: string
  @column()
  declare maxPossible: number
  @column()
  declare points: number
  @column()
  declare raceId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: string
}

export class SeasonSchema extends BaseModel {
  static $columns = ['createdAt', 'updatedAt', 'year'] as const
  $columns = SeasonSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column({ isPrimary: true })
  declare year: number
}

export class StageResultSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'raceId', 'rank', 'resultAt', 'resultType', 'riderId', 'stageNumber', 'updatedAt'] as const
  $columns = StageResultSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare raceId: string
  @column()
  declare rank: number
  @column.dateTime()
  declare resultAt: DateTime | null
  @column()
  declare resultType: string
  @column()
  declare riderId: string
  @column()
  declare stageNumber: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class StageSchema extends BaseModel {
  static $columns = ['createdAt', 'date', 'id', 'name', 'number', 'profileIcon', 'raceId', 'updatedAt'] as const
  $columns = StageSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare date: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare number: number
  @column()
  declare profileIcon: string | null
  @column()
  declare raceId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'googleId', 'icon', 'id', 'isSuperAdmin', 'notificationsEnabled', 'passwordHash', 'pseudo', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare googleId: string | null
  @column()
  declare icon: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isSuperAdmin: boolean
  @column()
  declare notificationsEnabled: boolean
  @column()
  declare passwordHash: string | null
  @column()
  declare pseudo: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}
